macmenu Edit.Find.Find\ Next key=<Nop>
macmenu Edit.Find.Find\ Previous key=<Nop>
macmenu Edit.Find.Use\ Selection\ for\ Find key=<Nop>
macmenu File.Open\ Tab\.\.\. key=<Nop>
macmenu File.Print key=<Nop>
macmenu Tools.List\ Errors key=<Nop>
macmenu Tools.Make key=<Nop>
macmenu Tools.Spelling.Suggest\ Corrections key=<Nop>
macmenu Tools.Spelling.To\ Next\ Error key=<Nop>
