let g:ruby_indent_access_modifier_style = 'indent'
let g:ruby_indent_assignment_style      = 'variable'
let g:ruby_indent_block_style           = 'do'
let g:rubycomplete_buffer_loading       = 1
let g:rubycomplete_classes_in_global    = 1
let g:rubycomplete_include_object       = 1
let g:rubycomplete_include_objectspace  = 1
let ruby_fold                           = 1
let ruby_foldable_groups                = 'def # __END__'
let ruby_spellcheck_strings             = 1
